### ISSUE TITLE
Plater Nameplates Module

### ISSUE THREAD

**Issue by Ghostamoose** [Total-RP/Total-RP-3#658]
**Integrated Plater Nameplates support for TRP3**

The goal for the initial release is (tentatively) a functional replacement for default nameplates for those using Plater. 

Only supports the default profile as of right now.

**Tasks**

Required:

- [x] Localization complete
  - [ ] Review
- [ ] Update changelog (leaving this one to @Meorawr or @Solanya to handle)
- [ ] Approval from the Mascot

Future plans:

- [ ] Nameplates for pets/battle pets with RP profiles
- [x] Better icon placement (need feedback for this one)
- [ ] Friend coloring
- [x] Guildmate coloring
- [x] Support for non-default Plater profiles (I see this as essential in the long-term)

**Comment by Ghostamoose** [comment]
This task still stands as a checklist for what I'm hoping to accomplish, but the module has been removed in favor of a standalone Plater mod, rather than a built-in TRP module.
